# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(verbose_name='цена'),
        ),
    ]
