# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20170423_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='cars/photos', verbose_name='фотография'),
        ),
    ]
